### ISSUE TITLE
Dask performance report not capturing task stream

### ISSUE THREAD

**Issue by beckernick** [rapidsai/gpu-bdb#116]
The Dask performance report does not seem to be capturing the task stream as part of the report. May be a general issue (not related to this codebase)

**Comment by jrbourbeau** [comment]
There was an issue in bokeh that caused the task stream to stop rendering (xref https://github.com/dask/distributed/issues/4161). Upgrading to the latest bokeh release (`bokeh==2.2.3`) should fix the issue

**Comment by beckernick** [comment]
Thanks @jrbourbeau ! Confirmed this is no longer an issue.
