### ISSUE TITLE
Query failure when using subset of GPUs on multi_GPU node

### ISSUE THREAD

**Issue by rfvander** [rapidsai/gpu-bdb#138]
I am trying to run TPCx-BB query 01 on 4 GPUs of a 16-GPU GV100 DGX-2 node. I set num_workers in file benchmark_config.yaml to 4, start the conda environment, launch my cluster with ROLE=SCHEDULER and CLUSTER_MODE="TCP". However, the query apparently expects me to use the entire node, not just my allocation within it, see error message below.

(rapids-tpcx-bb) robv@xpl-cr-85:/home/scratch.robv_gpu_1/apps/rapids/tpcx-bb-2/tpcx_bb/queries/q01$ python tpcx_bb_query_$query.py --config_file=../../benchmark_runner/benchmark_config_nsys.yaml
Using default arguments
{
  "type": "Scheduler",
  "id": "Scheduler-d014b83b-e31c-48f0-9180-5a470c6a518f",
  "address": "tcp://10.33.14.85:8786",
  "services": {
    "dashboard": 8787
  },
  "workers": {}
}
Connected!
Expected 16 32GB workers in your cluster, but got 4. It can take a moment for all workers to join the cluster. You may also have misconfigred hosts.
(rapids-tpcx-bb) robv@xpl-cr-85:/home/scratch.robv_gpu_1/apps/rapids/tpcx-bb-2/tpcx_bb/queries/q01$ nvidia-smi
Fri Nov 13 15:23:51 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM3...  On   | 00000000:36:00.0 Off |                    0 |
| N/A   29C    P0    68W / 350W |  28960MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM3...  On   | 00000000:39:00.0 Off |                    0 |
| N/A   34C    P0    69W / 350W |  28960MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM3...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0    70W / 350W |  28960MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM3...  On   | 00000000:57:00.0 Off |                    0 |
| N/A   29C    P0    67W / 350W |  28960MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     72910      C   ...rapids-tpcx-bb/bin/python    28957MiB |
|    1   N/A  N/A     72913      C   ...rapids-tpcx-bb/bin/python    28957MiB |
|    2   N/A  N/A     72911      C   ...rapids-tpcx-bb/bin/python    28957MiB |
|    3   N/A  N/A     72917      C   ...rapids-tpcx-bb/bin/python    28957MiB |
+-----------------------------------------------------------------------------+

**Comment by beckernick** [comment]
If this hasn't been resolved, can you provide the contents of `../../benchmark_runner/benchmark_config_nsys.yaml`?

I'm unable to reproduce this on a different machine than the one you are using

**Comment by rfvander** [comment]
Issue resolved by removing ~/.cudf
