### ISSUE TITLE
Data generation for tpc-xbb

### ISSUE THREAD

**Issue by nirandaperera** [rapidsai/gpu-bdb#181]
Hi, 

How do we generate the TPCx-BB dataset for this benchmark?

Best

**Comment by beckernick** [comment]
Hi @nirandaperera ! The [TPCxBB site](http://www.tpc.org/tpcx-bb/) provides a downloadable toolkit for generating data for TPCx-BB.

Please note that gpu-bdb is derived from TPCx-BB. Any results based on gpu-bdb are considered unofficial results, and per TPC policy, cannot be compared against official TPCx-BB results.

**Comment by nirandaperera** [comment]
hi @beckernick I was able to generate the csv files using the pdgf.jar. But I see that the benchmark implementation is using parquet. Is there a util to convert csv (.dat) files to parquet?
