### ISSUE TITLE
Switch Q03 to use the dropna public API. 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/gpu-bdb#228]
Switch out code at https://github.com/rapidsai/gpu-bdb/blob/main/gpu_bdb/queries/q03/gpu_bdb_query_03.py#L68 to below: 
```python
wcs_df = wcs_df.dropna(axis=0, subset=["wcs_user_sk", "wcs_item_sk"])
```

**Comment by bdice** [comment]
The internal API for `drop_nan=False` will be removed in https://github.com/rapidsai/cudf/pull/10140. Thanks @VibhuJawa for confirming that the public API will work here! 👍

**Comment by VibhuJawa** [comment]
Fixed by https://github.com/ChrisJar/gpu-bdb/pull/10 in  https://github.com/rapidsai/gpu-bdb/pull/224.
