### ISSUE TITLE
Ensure we generate and use dedicated serving data

### ISSUE THREAD

**Issue by seberg** [rapidsai/gpu-bdb#268]
I just realized that my old output folder with data has a `serving` and `training` folder.  I suspect we need to generate data for both serving and training and I _think_ we currently do not have a step for creating it (or use it).

CC @csadorf I suspect this is simple and relatively low prio, because it is easy to fix things up if we want it.

**Comment by csadorf** [comment]
Yes, you are correct that we should split training and serving data. I kind of intentionally "forgot" about that to not overcomplicate things in that first iteration, but we can quickly add that. I'll take care of that.

**Comment by seberg** [comment]
ooops, sorry wrong repo, had this randomly open!
